enableTelemetry: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@ArTs/plugin-http-proxy.cjs
    spec: 'https://github.com/arontsang/yarn-plugin-http-proxy/releases/latest/download/index.cjs'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
