# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CYPRESS_INSTALL_BINARY: 0
    strategy:
      matrix:
        node-version: [16.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
          cache: 'yarn'
      - run: |
          npm install -g pkg-fetch
          pkg-fetch --platform linux --node-range node16
          pkg-fetch --platform mac --node-range node16
          pkg-fetch --platform win --node-range node16
      - run: |
          yarn install --immutable --inline-builds
          yarn run release:all
          chmod +x release/mac/RedEye
          chmod +x release/linux/RedEye
      - name: Archive mac production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mac
          path: release/mac
      - name: Archive linux production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: release/linux
      - name: Archive windows production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: release/windows
