name: Cypress Tests

concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

on:
 # manual button click from the GitHub UI
 workflow_dispatch:
 push:
  branches:
   - main
   - develop
 pull_request:
  branches:
   - '**'

jobs:
 install:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Cache
     uses: actions/setup-node@v3
     with:
      cache: 'yarn'
   - run: yarn install
   - run: yarn build:all

   - name: Save build folder
     uses: actions/upload-artifact@v3
     with:
      name: dist
      if-no-files-found: error
      path: dist

 chrome:
  runs-on: ubuntu-latest
  container:
   image: cypress/browsers:node18.12.0-chrome106-ff106
  needs: install
  strategy:
   fail-fast: false
   matrix:
    containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Cache
     uses: actions/setup-node@v3
     with:
      cache: 'yarn'

   - name: Download the build folders
     uses: actions/download-artifact@v3
     with:
      name: dist
      path: dist

   - name: 'UI Tests - Chrome'
     uses: cypress-io/github-action@v4
     with:
      start: yarn start
      wait-on: 'http://localhost:4000/api/graphql, http://localhost:3500'
      browser: chrome
      group: 'Chrome'
      working-directory: applications/redeye-e2e
      config: baseUrl=http://localhost:3500
      record: true
      parallel: true
      config-file: cypress.config.js
     env:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 firefox:
  runs-on: ubuntu-latest
  container:
   image: cypress/browsers:node18.12.0-chrome106-ff106
   options: --user 1001
  needs: install
  strategy:
   fail-fast: false
   matrix:
    containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Cache
     uses: actions/setup-node@v3
     with:
      cache: 'yarn'

   - name: Download the build folders
     uses: actions/download-artifact@v3
     with:
      name: dist
      path: dist

   - name: 'UI Tests - Firefox'
     uses: cypress-io/github-action@v4
     with:
      start: yarn start
      wait-on: 'http://localhost:4000/api/graphql, http://localhost:3500'
      browser: firefox
      group: 'Firefox'
      working-directory: applications/redeye-e2e
      config: baseUrl=http://localhost:3500
      record: true
      parallel: true
      config-file: cypress.config.js
     env:
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
